version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: metro_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: metro_portal
      MYSQL_USER: metro
      MYSQL_PASSWORD: metro123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: metro_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root123
    ports:
      - "8080:80"

volumes:
  db_data:
